apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yh6jxes70-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yh6jxes70-go 
  name: yh6jxes70-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yh6jxes70-go 
